layout_spectrum: 0.6586506748571992
typography_spectrum: 0.6332714990712702
color:
  saturation: 0.41068246006034315
  brandStrength: 0.044056894490495324
  lightness: 0.4340352644212544
  brandColors:
    - '#FFFFFF'
    - '#CCCCCC'
    - '#999999'
    - '#4D4D4D'
    - '#333333'
  rhythmicContrast: 0.5905374716967344
opengraph:
  image: null
  type: null
  appId: null
analytics:
  twitter: null
  google: null
  facebook: null
name: Basalt
cta:
  bucket: null
  version: null
  domain: null
navigation:
  - name: My Studio
    url: 'http://www.basa.lt'
    type: external
favicon: null
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
title: MICHAEL MOULTON
description: DESIGNER // MUSIC SNOB
purpose: []
