name: Basalt
favicon: null
layout_spectrum: 0.6746767193544656
typography_spectrum: 0.3236272579524666
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#2a2c2b'
    - '#d9cb9e'
    - '#1e1e20'
    - '#374140'
    - '#dc3522'
  brandStrength: 0.12015054584480822
  lightness: 0.35216894117183983
  saturation: 0.4344483797904104
  rhythmicContrast: 0.19869695929810405
purpose: []
