typography_spectrum: 0.1899642
color:
  saturation: 0.4344483797904104
  brandStrength: 0.874552
  lightness: 0.3521689411718398
  brandColors:
    - '#2a2c2b'
    - '#d9cb9e'
    - '#1e1e20'
    - '#374140'
    - '#dc3522'
  rhythmicContrast: 0.198696959298104
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.188172
analytics:
  twitter: null
  google: null
  facebook: null
name: Basalt
cta:
  bucket: null
  version: null
  domain: null
navigation:
  - name: My Studio
    url: 'http://www.basa.lt'
    type: external
favicon: null
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
title: MICHAEL MOULTON
description: DESIGNER // MUSIC SNOB
purpose: []
